### ISSUE TITLE
Cleanliness of Code

### ISSUE THREAD

**Issue by luckydesignlady** [chasallen/web-iv-portfolio-site#1]
Proficient

No special characters noticed, and spacing is consistent.

Personal issue: I feel that the spacing between nested elements might be too much, because as the length of code increases, the text wraps and creates awkward short lines of code at the left side of the code box that are actually the end of the line above them. Just something to think about. I could be wrong, but I think that Ella noted a personal preference of 2 spaces per indent level when using the formatter (freeformatter.com), or up to a full tab. I think any more than that is overkill, and actually makes the code more difficult to read, in the end.
![screen shot 2015-05-16 at 11 46 43 am](https://cloud.githubusercontent.com/assets/8355247/7667043/48cfe8f6-fbc1-11e4-9c40-97af50ca2b78.png)

**Comment by e-m-durham** [comment]
Yep, only indent once for a nested element. Space, return, place comments consistently in your markup

Indent in css consistently, add spaces consistently.

Run your code through a code formatter for an easy boost in this criteria.

**Comment by e-m-durham** [comment]
No need to define a large and medium columns the same number wide. Foundation works mobile first and will inherit from definitions of smaller screen sizes.

**Comment by e-m-durham** [comment]
Group selectors when it makes sense, especially when they have identical properties.

```
header {
    padding-top: 25px;
}

section {
    padding-top: 100px;
}

.row-pad  {
    padding-top: 25px;
}

footer {
    padding-top: 100px;
}
```

could be 

```
header, .row-pad {
    padding-top: 25px;
}

section, footer {
    padding-top: 100px;
}
```
