### ISSUE TITLE
Directory Organization

### ISSUE THREAD

**Issue by luckydesignlady** [chasallen/web-iv-portfolio-site#3]
Proficient

Directory is properly organized, but some images are numbered. I feel that a more descriptive label would be helpful, instead of numbers.

**Comment by e-m-durham** [comment]
I agree, you'd want your image name to be more descriptive than a series of numbers. It's great to append with the image name and then give a very short description.

For example: 
hand-eater-poster.jpg 
hand-eater-detail-photo-manipulation.jpg

But also, I think you may want to think about image naming strategy overall for your images. Is "hand eater" the name of the project? Are those keywords that give important information about the work?

**Comment by e-m-durham** [comment]
Scripts do need to be cleaned up to only what you are using, right now that's a lot of "code bloat" that's why you want to download the essentials or a custom foundation build.
