### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by luckydesignlady** [chasallen/web-iv-portfolio-site#5]
Unsatisfactory

On mobile - 
-the social icons in the navigation are ginormous! I looked into your code, and noticed that you only have column settings for large and medium screen sizes, so on small screens, they fill the entire width of the screen. 

-I would like to see mobile navigation implemented. Right now, the links are as-is, and might be confusing to find or difficult to click

-The iframe extends beyond the mobile grid, but I don’t know if there’s anything that can be done about that or not. To be honest, most of the sites I click on and view on my phone show the iframe funny, and I have to click on it to view it properly anyways. (I very recently figured this out. In the past...I just skipped the video that I could only see half of. So...look into it, if you haven’t!)

-When you collapse to mobile size, the about section feels very out of place within the footer. I would look into foundation’s visibility classes to hide this for mobile, or maybe find a way to collapse it so that it’s a button or accordion tab or something on mobile, so that it doesn’t look like it does not belong there. 

-On medium screen sizes, the top two rectangular shapes (placeholder images) feel really out of place off to the side, like they are.

**Comment by e-m-durham** [comment]
Really thorough review on this criteria, @luckydesignlady!

**Comment by e-m-durham** [comment]
For the video http://alistapart.com/d/creating-intrinsic-ratios-for-video/example3.html
