### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by luckydesignlady** [chasallen/web-iv-portfolio-site#6]
Satisfactory

This was great, until I looked into your type hierarchy a bit closer… :)

index.html - 
-has no h1 at all, but in the footer, you start with a < h3 >.
    Be sure to style type with css, not with h1’s through h6’s.
        This is important for:
            -accessibility (like screen readers for the visually impaired)
            -SEO, baby! You want search engines to be able to easily understand you site’s ‘content outline’.

project-so-and-so.html -
-has an h2, but no h2, and the h3 pattern is continued in the footer, as before.

**Comment by e-m-durham** [comment]
Yep, @luckydesignlady is right, make sure you're using heading levels in a way that makes your document outline make sense.
