### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by luckydesignlady** [chasallen/web-iv-portfolio-site#8]
Proficient

I feel like the ‘contact me’ link in the nav a lot. In fact, if you don’t mind, I’d love to grab the code to open it from you, because I don’t really want a contact ‘form’, either.
    My issue is it being in the navigation, because I expect nav links to take me to another part of the site, instead of opening a window on my computer. That’s perfect for people like us who are always logged in, but people on shared computers will most likely close that email window as soon as it opens, then search for your email address so that they can contact you. I usually only expect that window to open when I click  on the email address itself. 
    My best solution to this issue would be to possibly have this nav link point to your footer with your contact info, and make that email address clickable, so that they can either click on it, expecting an email box to pop up, or copy & paste your email address into their browser-based email’s “to” field, if it’s their habit to do so.

**Comment by e-m-durham** [comment]
This is a really good point, @luckydesignlady brings up. I think that could potentially cause confusion and irritation for the user as well. 

I think my concern is more in the navigation, primarily on smaller screens. Maybe refer to https://bradfrost.github.io/this-is-responsive/patterns.html#navigation for some potential solutions.

**Comment by e-m-durham** [comment]
Previous and next buttons don't necessarily have to be text but if you use text in addition to an icon you should not "paint the text." It'll be more accessible if you have 'Next Project' typed out rather than saved out in an image. I'm just doing a quick compare to your wireframe and noticed you just have those buttons as images in this commit of the prototype.

**Comment by e-m-durham** [comment]
I'm assuming you're going the ticket/slider route here and that you just hadn't gotten to the slider quite yet. It would be best to work out the details of that before you move onto stylizing the site and self-evaluate or come back to me to reevaluate the user experience on the landing page again at that point.

**Comment by e-m-durham** [comment]
I'd stray away from changing the links in your navigation. I think this is something Sam and I might have pointed out when looking at your wireframes. It can become disorienting to go from one page to the other and have the primary navigation change. You can make a visual indication that you are on the "Design" page, but don't replace it with "Home." Also, I would probably expect to see a sampling or a single page on "Design" not just one single project. It's something you may have to consider further.
